export interface Country {
  code: string;
  name: string;
  flag: string;
}

export const COUNTRIES: Country[] = [
  { code: "NG", name: "Nigeria",          flag: "🇳🇬" },
  { code: "US", name: "United States",    flag: "🇺🇸" },
  { code: "GB", name: "United Kingdom",   flag: "🇬🇧" },
  { code: "GH", name: "Ghana",            flag: "🇬🇭" },
  { code: "KE", name: "Kenya",            flag: "🇰🇪" },
  { code: "ZA", name: "South Africa",     flag: "🇿🇦" },
  { code: "CA", name: "Canada",           flag: "🇨🇦" },
  { code: "AU", name: "Australia",        flag: "🇦🇺" },
  { code: "IN", name: "India",            flag: "🇮🇳" },
  { code: "AE", name: "United Arab Emirates", flag: "🇦🇪" },
  { code: "DE", name: "Germany",          flag: "🇩🇪" },
  { code: "FR", name: "France",           flag: "🇫🇷" },
  { code: "TZ", name: "Tanzania",         flag: "🇹🇿" },
  { code: "UG", name: "Uganda",           flag: "🇺🇬" },
  { code: "ET", name: "Ethiopia",         flag: "🇪🇹" },
  { code: "EG", name: "Egypt",            flag: "🇪🇬" },
  { code: "MA", name: "Morocco",          flag: "🇲🇦" },
  { code: "SN", name: "Senegal",          flag: "🇸🇳" },
  { code: "CM", name: "Cameroon",         flag: "🇨🇲" },
  { code: "CI", name: "Côte d'Ivoire",    flag: "🇨🇮" },
  { code: "PK", name: "Pakistan",         flag: "🇵🇰" },
  { code: "BD", name: "Bangladesh",       flag: "🇧🇩" },
  { code: "PH", name: "Philippines",      flag: "🇵🇭" },
  { code: "NG", name: "Nigeria",          flag: "🇳🇬" },
  { code: "BR", name: "Brazil",           flag: "🇧🇷" },
  { code: "MX", name: "Mexico",           flag: "🇲🇽" },
  { code: "NL", name: "Netherlands",      flag: "🇳🇱" },
  { code: "SE", name: "Sweden",           flag: "🇸🇪" },
  { code: "NO", name: "Norway",           flag: "🇳🇴" },
  { code: "IT", name: "Italy",            flag: "🇮🇹" },
  { code: "ES", name: "Spain",            flag: "🇪🇸" },
  { code: "NZ", name: "New Zealand",      flag: "🇳🇿" },
  { code: "SG", name: "Singapore",        flag: "🇸🇬" },
  { code: "MY", name: "Malaysia",         flag: "🇲🇾" },
  { code: "NG", name: "Nigeria",          flag: "🇳🇬" },
];

// Deduplicate by code
const seen = new Set<string>();
export const UNIQUE_COUNTRIES = COUNTRIES.filter((c) => {
  if (seen.has(c.code)) return false;
  seen.add(c.code);
  return true;
});

export interface StateEntry {
  name: string;
  cities: string[];
}

export const STATES_BY_COUNTRY: Record<string, StateEntry[]> = {
  NG: [
    { name: "Lagos",          cities: ["Lagos Island", "Ikeja", "Victoria Island", "Lekki", "Surulere", "Yaba", "Ikorodu", "Alimosho"] },
    { name: "Abuja (FCT)",    cities: ["Garki", "Wuse", "Maitama", "Asokoro", "Gwarinpa", "Kubwa", "Nyanya"] },
    { name: "Kano",           cities: ["Kano City", "Fagge", "Gwale", "Dala", "Nasarawa", "Tarauni"] },
    { name: "Rivers",         cities: ["Port Harcourt", "Obio-Akpor", "Bonny", "Eleme", "Oyigbo"] },
    { name: "Oyo",            cities: ["Ibadan", "Ogbomosho", "Oyo", "Iseyin", "Saki"] },
    { name: "Kaduna",         cities: ["Kaduna", "Zaria", "Kafanchan", "Kagoro"] },
    { name: "Enugu",          cities: ["Enugu", "Nsukka", "Oji River", "Awgu"] },
    { name: "Delta",          cities: ["Warri", "Asaba", "Sapele", "Ughelli", "Agbor"] },
    { name: "Anambra",        cities: ["Awka", "Onitsha", "Nnewi", "Ekwulobia"] },
    { name: "Imo",            cities: ["Owerri", "Orlu", "Okigwe", "Oguta"] },
    { name: "Edo",            cities: ["Benin City", "Auchi", "Ekpoma", "Uromi"] },
    { name: "Cross River",    cities: ["Calabar", "Ikom", "Ogoja", "Ugep"] },
    { name: "Akwa Ibom",      cities: ["Uyo", "Eket", "Ikot Ekpene", "Oron"] },
    { name: "Ogun",           cities: ["Abeokuta", "Sagamu", "Ijebu-Ode", "Ota"] },
    { name: "Osun",           cities: ["Osogbo", "Ile-Ife", "Ilesa", "Ede"] },
    { name: "Kwara",          cities: ["Ilorin", "Offa", "Lokoja", "Lafiagi"] },
    { name: "Niger",          cities: ["Minna", "Suleja", "Bida", "Kontagora"] },
    { name: "Borno",          cities: ["Maiduguri", "Biu", "Gwoza", "Damboa"] },
    { name: "Sokoto",         cities: ["Sokoto", "Tambuwal", "Binji", "Illela"] },
    { name: "Plateau",        cities: ["Jos", "Bukuru", "Shendam", "Pankshin"] },
    { name: "Bauchi",         cities: ["Bauchi", "Azare", "Misau", "Katagum"] },
    { name: "Gombe",          cities: ["Gombe", "Kumo", "Billiri", "Bajoga"] },
    { name: "Adamawa",        cities: ["Yola", "Mubi", "Numan", "Ganye"] },
    { name: "Taraba",         cities: ["Jalingo", "Wukari", "Bali", "Takum"] },
    { name: "Benue",          cities: ["Makurdi", "Gboko", "Katsina-Ala", "Otukpo"] },
    { name: "Kogi",           cities: ["Lokoja", "Okene", "Kabba", "Idah"] },
    { name: "Nassarawa",      cities: ["Lafia", "Keffi", "Akwanga", "Doma"] },
    { name: "Zamfara",        cities: ["Gusau", "Kaura Namoda", "Anka", "Talata Mafara"] },
    { name: "Kebbi",          cities: ["Birnin Kebbi", "Argungu", "Zuru", "Yauri"] },
    { name: "Jigawa",         cities: ["Dutse", "Hadejia", "Gumel", "Kazaure"] },
    { name: "Katsina",        cities: ["Katsina", "Daura", "Funtua", "Mashi"] },
    { name: "Yobe",           cities: ["Damaturu", "Potiskum", "Gashua", "Nguru"] },
    { name: "Abia",           cities: ["Umuahia", "Aba", "Ohafia", "Bende"] },
    { name: "Ebonyi",         cities: ["Abakaliki", "Afikpo", "Onueke", "Ezza"] },
    { name: "Bayelsa",        cities: ["Yenagoa", "Brass", "Ogbia", "Sagbama"] },
    { name: "Ekiti",          cities: ["Ado Ekiti", "Ikere", "Ikole", "Oye"] },
    { name: "Ondo",           cities: ["Akure", "Ondo", "Ikare", "Ore"] },
  ],
  US: [
    { name: "California",      cities: ["Los Angeles", "San Francisco", "San Diego", "San Jose", "Sacramento", "Oakland", "Fresno"] },
    { name: "Texas",           cities: ["Houston", "Dallas", "Austin", "San Antonio", "Fort Worth", "El Paso", "Arlington"] },
    { name: "Florida",         cities: ["Miami", "Orlando", "Tampa", "Jacksonville", "Fort Lauderdale", "Tallahassee"] },
    { name: "New York",        cities: ["New York City", "Buffalo", "Rochester", "Yonkers", "Syracuse", "Albany"] },
    { name: "Illinois",        cities: ["Chicago", "Aurora", "Naperville", "Joliet", "Rockford", "Springfield"] },
    { name: "Pennsylvania",    cities: ["Philadelphia", "Pittsburgh", "Allentown", "Erie", "Reading"] },
    { name: "Ohio",            cities: ["Columbus", "Cleveland", "Cincinnati", "Toledo", "Akron", "Dayton"] },
    { name: "Georgia",         cities: ["Atlanta", "Augusta", "Columbus", "Macon", "Savannah"] },
    { name: "North Carolina",  cities: ["Charlotte", "Raleigh", "Greensboro", "Durham", "Winston-Salem"] },
    { name: "Michigan",        cities: ["Detroit", "Grand Rapids", "Warren", "Sterling Heights", "Ann Arbor"] },
    { name: "New Jersey",      cities: ["Newark", "Jersey City", "Paterson", "Elizabeth", "Trenton"] },
    { name: "Virginia",        cities: ["Virginia Beach", "Norfolk", "Chesapeake", "Richmond", "Arlington"] },
    { name: "Washington",      cities: ["Seattle", "Spokane", "Tacoma", "Vancouver", "Bellevue"] },
    { name: "Arizona",         cities: ["Phoenix", "Tucson", "Mesa", "Chandler", "Scottsdale", "Tempe"] },
    { name: "Massachusetts",   cities: ["Boston", "Worcester", "Springfield", "Cambridge", "Lowell"] },
    { name: "Tennessee",       cities: ["Nashville", "Memphis", "Knoxville", "Chattanooga", "Clarksville"] },
    { name: "Indiana",         cities: ["Indianapolis", "Fort Wayne", "Evansville", "South Bend", "Carmel"] },
    { name: "Missouri",        cities: ["Kansas City", "St. Louis", "Springfield", "Columbia", "Independence"] },
    { name: "Maryland",        cities: ["Baltimore", "Columbia", "Germantown", "Silver Spring", "Waldorf"] },
    { name: "Colorado",        cities: ["Denver", "Colorado Springs", "Aurora", "Fort Collins", "Lakewood"] },
    { name: "Wisconsin",       cities: ["Milwaukee", "Madison", "Green Bay", "Kenosha", "Racine"] },
    { name: "Minnesota",       cities: ["Minneapolis", "Saint Paul", "Rochester", "Duluth", "Bloomington"] },
    { name: "Nevada",          cities: ["Las Vegas", "Henderson", "Reno", "North Las Vegas", "Sparks"] },
    { name: "Louisiana",       cities: ["New Orleans", "Baton Rouge", "Shreveport", "Lafayette", "Lake Charles"] },
    { name: "Alabama",         cities: ["Birmingham", "Montgomery", "Huntsville", "Mobile", "Tuscaloosa"] },
  ],
  GB: [
    { name: "England",         cities: ["London", "Birmingham", "Manchester", "Leeds", "Liverpool", "Sheffield", "Bristol", "Leicester", "Coventry", "Bradford", "Nottingham", "Kingston upon Hull"] },
    { name: "Scotland",        cities: ["Glasgow", "Edinburgh", "Aberdeen", "Dundee", "Inverness", "Perth"] },
    { name: "Wales",           cities: ["Cardiff", "Swansea", "Newport", "Bangor", "St Davids"] },
    { name: "Northern Ireland",cities: ["Belfast", "Derry", "Lisburn", "Newry", "Armagh"] },
  ],
  GH: [
    { name: "Greater Accra",   cities: ["Accra", "Tema", "Madina", "Kasoa", "Ashaiman"] },
    { name: "Ashanti",         cities: ["Kumasi", "Obuasi", "Ejisu", "Mampong"] },
    { name: "Western",         cities: ["Takoradi", "Sekondi", "Tarkwa", "Axim"] },
    { name: "Central",         cities: ["Cape Coast", "Winneba", "Kasoa", "Swedru"] },
    { name: "Eastern",         cities: ["Koforidua", "Nkawkaw", "Akim Oda", "Nsawam"] },
    { name: "Northern",        cities: ["Tamale", "Yendi", "Bimbilla", "Salaga"] },
    { name: "Upper East",      cities: ["Bolgatanga", "Bawku", "Navrongo", "Zebilla"] },
    { name: "Upper West",      cities: ["Wa", "Lawra", "Tumu", "Jirapa"] },
    { name: "Volta",           cities: ["Ho", "Hohoe", "Keta", "Kpando"] },
    { name: "Brong-Ahafo",     cities: ["Sunyani", "Berekum", "Techiman", "Kintampo"] },
  ],
  ZA: [
    { name: "Gauteng",         cities: ["Johannesburg", "Pretoria", "Soweto", "Ekurhuleni", "Centurion", "Sandton"] },
    { name: "Western Cape",    cities: ["Cape Town", "Stellenbosch", "George", "Paarl", "Mossel Bay"] },
    { name: "KwaZulu-Natal",   cities: ["Durban", "Pietermaritzburg", "Richards Bay", "Newcastle", "Ballito"] },
    { name: "Eastern Cape",    cities: ["Port Elizabeth", "East London", "Mthatha", "Queenstown"] },
    { name: "Limpopo",         cities: ["Polokwane", "Tzaneen", "Mokopane", "Louis Trichardt"] },
    { name: "Mpumalanga",      cities: ["Nelspruit", "Witbank", "Middelburg", "Secunda"] },
    { name: "North West",      cities: ["Rustenburg", "Klerksdorp", "Mafikeng", "Potchefstroom"] },
    { name: "Free State",      cities: ["Bloemfontein", "Welkom", "Bethlehem", "Sasolburg"] },
    { name: "Northern Cape",   cities: ["Kimberley", "Upington", "Springbok", "De Aar"] },
  ],
  KE: [
    { name: "Nairobi",         cities: ["Nairobi CBD", "Westlands", "Kasarani", "Embakasi", "Dagoretti", "Lang'ata"] },
    { name: "Mombasa",         cities: ["Mombasa Island", "Likoni", "Kisauni", "Nyali", "Changamwe"] },
    { name: "Kisumu",          cities: ["Kisumu City", "Nyalenda", "Kondele", "Migosi"] },
    { name: "Nakuru",          cities: ["Nakuru Town", "Naivasha", "Gilgil", "Molo"] },
    { name: "Kiambu",          cities: ["Thika", "Kiambu Town", "Ruiru", "Limuru", "Kikuyu"] },
    { name: "Machakos",        cities: ["Machakos Town", "Athi River", "Kangundo", "Matuu"] },
    { name: "Uasin Gishu",     cities: ["Eldoret", "Turbo", "Moiben", "Burnt Forest"] },
    { name: "Meru",            cities: ["Meru Town", "Nkubu", "Chuka", "Maua"] },
    { name: "Kilifi",          cities: ["Malindi", "Kilifi Town", "Watamu", "Kaloleni"] },
    { name: "Trans Nzoia",     cities: ["Kitale", "Endebess", "Saboti"] },
  ],
  CA: [
    { name: "Ontario",         cities: ["Toronto", "Ottawa", "Mississauga", "Brampton", "Hamilton", "London", "Markham", "Windsor"] },
    { name: "Quebec",          cities: ["Montreal", "Quebec City", "Laval", "Gatineau", "Longueuil"] },
    { name: "British Columbia",cities: ["Vancouver", "Surrey", "Burnaby", "Richmond", "Kelowna", "Abbotsford"] },
    { name: "Alberta",         cities: ["Calgary", "Edmonton", "Red Deer", "Lethbridge", "Medicine Hat"] },
    { name: "Manitoba",        cities: ["Winnipeg", "Brandon", "Steinbach", "Thompson"] },
    { name: "Saskatchewan",    cities: ["Saskatoon", "Regina", "Prince Albert", "Moose Jaw"] },
    { name: "Nova Scotia",     cities: ["Halifax", "Sydney", "Dartmouth", "Truro"] },
    { name: "New Brunswick",   cities: ["Moncton", "Saint John", "Fredericton", "Miramichi"] },
    { name: "Newfoundland",    cities: ["St. John's", "Corner Brook", "Gander", "Grand Falls"] },
    { name: "Prince Edward Island", cities: ["Charlottetown", "Summerside", "Stratford"] },
  ],
  AU: [
    { name: "New South Wales", cities: ["Sydney", "Newcastle", "Wollongong", "Central Coast", "Maitland"] },
    { name: "Victoria",        cities: ["Melbourne", "Geelong", "Ballarat", "Bendigo", "Shepparton"] },
    { name: "Queensland",      cities: ["Brisbane", "Gold Coast", "Sunshine Coast", "Townsville", "Cairns"] },
    { name: "Western Australia",cities: ["Perth", "Mandurah", "Bunbury", "Geraldton", "Kalgoorlie"] },
    { name: "South Australia", cities: ["Adelaide", "Mount Gambier", "Whyalla", "Murray Bridge"] },
    { name: "Tasmania",        cities: ["Hobart", "Launceston", "Devonport", "Burnie"] },
    { name: "ACT",             cities: ["Canberra", "Belconnen", "Tuggeranong", "Woden"] },
    { name: "Northern Territory", cities: ["Darwin", "Alice Springs", "Palmerston", "Katherine"] },
  ],
  IN: [
    { name: "Maharashtra",     cities: ["Mumbai", "Pune", "Nagpur", "Nashik", "Aurangabad", "Solapur"] },
    { name: "Delhi",           cities: ["New Delhi", "Noida", "Gurgaon", "Faridabad", "Ghaziabad"] },
    { name: "Karnataka",       cities: ["Bengaluru", "Mysuru", "Mangaluru", "Hubli", "Belgaum"] },
    { name: "Tamil Nadu",      cities: ["Chennai", "Coimbatore", "Madurai", "Tiruchirappalli", "Salem"] },
    { name: "Telangana",       cities: ["Hyderabad", "Warangal", "Nizamabad", "Karimnagar"] },
    { name: "Gujarat",         cities: ["Ahmedabad", "Surat", "Vadodara", "Rajkot", "Bhavnagar"] },
    { name: "Rajasthan",       cities: ["Jaipur", "Jodhpur", "Kota", "Bikaner", "Ajmer"] },
    { name: "Uttar Pradesh",   cities: ["Lucknow", "Kanpur", "Agra", "Varanasi", "Allahabad", "Meerut"] },
    { name: "West Bengal",     cities: ["Kolkata", "Howrah", "Durgapur", "Asansol", "Siliguri"] },
    { name: "Punjab",          cities: ["Ludhiana", "Amritsar", "Jalandhar", "Patiala", "Bathinda"] },
    { name: "Kerala",          cities: ["Thiruvananthapuram", "Kochi", "Kozhikode", "Thrissur", "Kollam"] },
  ],
  AE: [
    { name: "Dubai",           cities: ["Downtown Dubai", "Deira", "Bur Dubai", "Jumeirah", "Dubai Marina", "Business Bay"] },
    { name: "Abu Dhabi",       cities: ["Abu Dhabi City", "Al Ain", "Musaffah", "Khalifa City"] },
    { name: "Sharjah",         cities: ["Sharjah City", "Khor Fakkan", "Kalba", "Dhaid"] },
    { name: "Ajman",           cities: ["Ajman City", "Masfout", "Manama"] },
    { name: "Ras Al Khaimah",  cities: ["RAK City", "Julfar", "Digdaga"] },
    { name: "Fujairah",        cities: ["Fujairah City", "Dibba", "Kalba"] },
    { name: "Umm Al Quwain",   cities: ["UAQ City", "Falaj Al Mualla"] },
  ],
  DE: [
    { name: "Bavaria",         cities: ["Munich", "Nuremberg", "Augsburg", "Regensburg", "Ingolstadt"] },
    { name: "Berlin",          cities: ["Mitte", "Charlottenburg", "Prenzlauer Berg", "Friedrichshain"] },
    { name: "Hamburg",         cities: ["Hamburg City", "Altona", "Eimsbüttel", "Wandsbek"] },
    { name: "North Rhine-Westphalia", cities: ["Cologne", "Düsseldorf", "Dortmund", "Essen", "Duisburg", "Bochum"] },
    { name: "Baden-Württemberg", cities: ["Stuttgart", "Karlsruhe", "Mannheim", "Freiburg", "Heidelberg"] },
    { name: "Hesse",           cities: ["Frankfurt", "Wiesbaden", "Kassel", "Darmstadt"] },
    { name: "Saxony",          cities: ["Leipzig", "Dresden", "Chemnitz", "Zwickau"] },
    { name: "Lower Saxony",    cities: ["Hannover", "Braunschweig", "Osnabrück", "Oldenburg"] },
  ],
  FR: [
    { name: "Île-de-France",   cities: ["Paris", "Boulogne-Billancourt", "Saint-Denis", "Argenteuil", "Montreuil"] },
    { name: "Auvergne-Rhône-Alpes", cities: ["Lyon", "Grenoble", "Saint-Étienne", "Clermont-Ferrand"] },
    { name: "Provence-Alpes-Côte d'Azur", cities: ["Marseille", "Nice", "Toulon", "Aix-en-Provence", "Cannes"] },
    { name: "Nouvelle-Aquitaine", cities: ["Bordeaux", "Limoges", "Pau", "Bayonne", "Poitiers"] },
    { name: "Occitanie",       cities: ["Toulouse", "Montpellier", "Nîmes", "Perpignan"] },
    { name: "Hauts-de-France", cities: ["Lille", "Amiens", "Roubaix", "Tourcoing"] },
    { name: "Grand Est",       cities: ["Strasbourg", "Reims", "Metz", "Nancy", "Mulhouse"] },
    { name: "Pays de la Loire", cities: ["Nantes", "Angers", "Le Mans", "Saint-Nazaire"] },
  ],
};

export function buildLocationString(country: string, state: string, city: string): string {
  const parts = [city.trim(), state.trim(), country.trim()].filter(Boolean);
  return parts.join(", ");
}

export function getStates(countryCode: string): StateEntry[] {
  return STATES_BY_COUNTRY[countryCode] ?? [];
}
