// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const REMEMBER_ME_STORAGE_KEY = "kodarai.remember-me";

/**
 * Store sessions in localStorage by default, but let someone explicitly opt
 * out of "Remember me" and keep their session only for the current browser
 * tab. Keeping this adapter here also makes the choice work for Google OAuth.
 */
function createBrowserSessionStorage() {
  const usesPersistentStorage = () =>
    window.localStorage.getItem(REMEMBER_ME_STORAGE_KEY) !== "false";

  return {
    getItem: (key: string) =>
      (usesPersistentStorage() ? window.localStorage : window.sessionStorage).getItem(key),
    setItem: (key: string, value: string) => {
      const activeStorage = usesPersistentStorage() ? window.localStorage : window.sessionStorage;
      const inactiveStorage = usesPersistentStorage() ? window.sessionStorage : window.localStorage;
      activeStorage.setItem(key, value);
      inactiveStorage.removeItem(key);
    },
    removeItem: (key: string) => {
      window.localStorage.removeItem(key);
      window.sessionStorage.removeItem(key);
    },
  };
}

export function setRememberMe(rememberMe: boolean) {
  if (typeof window === "undefined") return;
  window.localStorage.setItem(REMEMBER_ME_STORAGE_KEY, String(rememberMe));
}

function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || process.env.SUPABASE_PUBLISHABLE_KEY;

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ['SUPABASE_PUBLISHABLE_KEY'] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(', ')}. Connect Supabase in Lovable Cloud.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: typeof window !== 'undefined' ? createBrowserSessionStorage() : undefined,
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: true,
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
